### ISSUE TITLE
Bug: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Rojikku** [SIMKL/Emby#11]
[embyserver.txt](https://github.com/SIMKL/Emby/files/4914757/embyserver.txt)
```
2020-07-13 11:55:22.017 Info Simkl Scrobbler: Trying to scrobble The Witch of Destruction (256705) for Rojikku (23a54396295844f587339c8a4aec85d4) - /data/tv/Shows/The Misfit of Demon King Academy - History's Strongest Demon King Reincarnates and Goes to School with His Descendants/Season 1/The Misfit of Demon King Academy - S01E02 - HDTV-1080p.mkv on f56e215f3071444daf9fab048de61da5
2020-07-13 11:55:22.023 Error Simkl Scrobbler: Caught unknown exception while trying to scrobble: Object reference not set to an instance of an object.
2020-07-13 11:55:22.023 Error Simkl Scrobbler:    at Simkl.Api.Objects.SimklIds..ctor(Dictionary`2 ProviderIds)
   at Simkl.Api.Objects.SimklShowIds..ctor(Dictionary`2 providerMovieIds)
   at Simkl.Api.Objects.SimklShow..ctor(BaseItemDto MediaInfo)
   at Simkl.Api.SimklApi.createHistoryFromItem(BaseItemDto item)
   at Simkl.Api.SimklApi.markAsWatched(BaseItemDto item, String userToken)
   at Simkl.Services.Scrobbler.embyPlaybackProgress(Object sessions, PlaybackProgressEventArgs e)
```

I've honestly never had this plugin for Simkl successfully mark an episode as watched, to the furthest extent of my knowledge. I have multiple users, premium Emby, it shows my users are setup, and scrobbling options are default (Enabled and 70%).
I am running Emby 4.4.3.0 but this has applied through all versions, and I am running it through Docker. I do most of my episode watching via the Samsung TV app.

**Comment by masyk** [comment]
Which metadata engine does it use to identify the show - TVDB or TMDB?

**Comment by Rojikku** [comment]
![IDs](https://user-images.githubusercontent.com/1676068/87348595-049ac300-c523-11ea-9698-9244f36a0b7b.png)
@masyk Does this help? I have TVDB Ids in the metadata, if I edit it. It looks like TMDB means TheMovieDb and that's apparently also in here.

**Comment by ekleop** [comment]
Unfortunately we cannot reproduce this bug right now. Seems like it's because of multiple users but need to check more. I hope we will fix it in the future release

**Comment by Rojikku** [comment]
I don't know if any of the following helps.

When I go into the Emby settings for the tracker, it shows me the latest created user in the dropdown, and my first linked account's settings (So it shows the wrong Simkl account, presumably just a UI bug).
If I changed my drop down selection it updates to everything being correct.

It shows my user as logged in. I have 2/4 users with Simkl accounts, previously 2/3 and 1/3. I'm running Emby from a docker container. 

I'm in the simkl discord as `@Rojikku` as well if you need to contact me for more information.

I hope you'll fix it in a future release as well. This plugin is why I switched to Simkl, and I've unfortunately never gotten it to work, and I don't know why.

**Comment by masyk** [comment]
What is the server OS and what is the emby server version?

**Comment by Rojikku** [comment]
> What is the server OS and what is the emby server version?

Er...That was in my first post. 4.4.3.0
https://hub.docker.com/r/linuxserver/emby
tag: latest

**Comment by ekleop** [comment]
bug was due new mediacore of emby. Soon should be updated in emby catalog
