### ISSUE TITLE
Crash on Scrobble

### ISSUE THREAD

**Issue by zacharyrs** [SIMKL/Emby#6]
Seems the Simkl API isn't quite working, so this plugin ended up crashing Emby...

```
emby-server[496626]: Unhandled Exception: MediaBrowser.Model.Net.HttpException: BadGateway
emby-server[496626]:    at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
emby-server[496626]:    at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
emby-server[496626]:    at Simkl.Api.SimklApi._post(String url, String userToken, Object data)
emby-server[496626]:    at Simkl.Api.SimklApi.SyncHistoryAsync(SimklHistory history, String userToken)
emby-server[496626]:    at Simkl.Api.SimklApi.markAsWatched(BaseItemDto item, String userToken)
emby-server[496626]:    at Simkl.Services.Scrobbler.embyPlaybackProgress(Object sessions, PlaybackProgressEventArgs e)
emby-server[496626]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
emby-server[496626]: --- End of stack trace from previous location where exception was thrown ---
emby-server[496626]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
XXX Info HttpClient: Http response 502 from http://private-XXX-simkl.apiary-proxy.com/sync/history after 544ms. HeadersDate=XXX, Connection=keep-alive, X-Apiary-RateLimit-Limit=120, X-Apiary-RateLimit-Remaining=115, x-apiary-transaction-id=XXX, Access-Control-Allow-Origin=*, Access-Control-Allow-Methods=OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT, Access-Control-Max-Age=10
XXX Error HttpClient: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by masyk** [comment]
Seems like there’s an apiary domain used instead of https://api.simkl.com for some reason on your setup

**Comment by zacharyrs** [comment]
Perhaps I'm running something a bit outdated..?

**Comment by Simkl-dev** [comment]
Looks like .dll file was compiled with a developer proxy url. Will compile a new one with a correct url.

**Comment by ekleop** [comment]
Tested, seems like you have an old dll, update it from the repo and everything should be fine.

**Comment by zacharyrs** [comment]
Yeah, must've been very outdated! Updated it now, so we'll have to see...
