### ISSUE TITLE
Bug: Certain movies erroring during Scrobbler

### ISSUE THREAD

**Issue by abarnwell** [SIMKL/Emby#9]
The Simkl plugin doesn't usually have a problem but for some reason on this particular movie it has. I've redacted the specific details but could PM if someone were available to help me diagnose. I'm wondering if it has something to do with the ':' in the movie name?

```
Info Simkl Scrobbler: Trying to scrobble Foo: Bar (79) for username (xxxxx) - /Movies/Foo Bar (2019)/Foo Bar (2019).mkv on xxxxx
2020-01-12 17:51:42.580 Error Simkl Scrobbler: Caught unknown exception while trying to scrobble: Object reference not set to an instance of an object.
2020-01-12 17:51:42.581 Error Simkl Scrobbler:    at Simkl.Api.Objects.SimklIds..ctor(Dictionary`2 ProviderIds)
   at Simkl.Api.Objects.SimklMovieIds..ctor(Dictionary`2 providerMovieIds)
   at Simkl.Api.Objects.SimklMovie..ctor(BaseItemDto item)
   at Simkl.Api.SimklApi.createHistoryFromItem(BaseItemDto item)
   at Simkl.Api.SimklApi.markAsWatched(BaseItemDto item, String userToken)
   at Simkl.Services.Scrobbler.embyPlaybackProgress(Object sessions, PlaybackProgressEventArgs e)
```

**Comment by ekleop** [comment]
What is the name of your file?
 /Movies/Foo Bar (2019)/Foo Bar (2019).mkv?

**Comment by AdamBarnwell** [comment]
> What is the name of your file?
> /Movies/Foo Bar (2019)/Foo Bar (2019).mkv?

@ekleop it was:
/Movies/Jumanji Welcome to the Jungle (2017)/Jumanji Welcome to the Jungle (2017).mkv

**Comment by abarnwell** [comment]
> What is the name of your file?
> /Movies/Foo Bar (2019)/Foo Bar (2019).mkv?

@ekleop, it was:
/Movies/Jumanji Welcome to the Jungle (2017)/Jumanji Welcome to the Jungle (2017).mkv
